/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projektas;


import java.util.Random;
import projektas.PriorityQueue.*;
import projektas.Player;
/**
 *
 * @author Martynas
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textar = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jButton1.setText("Poll");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Peek");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("IsEmpty");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Contains");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        textar.setColumns(20);
        textar.setRows(5);
        jScrollPane1.setViewportView(textar);

        jButton6.setText("Greitaveika");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Add)
                                .addComponent(jButton1)
                                .addComponent(jButton2)
                                .addComponent(jButton3)))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Add)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addGap(28, 28, 28)
                .addComponent(jButton3)
                .addGap(32, 32, 32)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
                
        
        int nr = 0;
        
        textar.append("\n");
        for(Player n : zaidMasyvas){
    
            eile.add(n, n.getMetai());
            textar.append(n.getVardas() +" "+n.getPavarde() +"  priority:"+ n.getMetai() + "\n");
        }
        
    }//GEN-LAST:event_AddActionPerformed

    


   
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (eile.isEmpty()==false)
            textar.append("\n"+eile.peek().getPavarde() +" "+eile.peek().getVardas()+" "+eile.peek().getMetai()+"\n");
        else
            textar.append("\neile tuscia");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (eile.isEmpty()==false){
        Player am = eile.poll();
        textar.append("\n"+am.getPavarde() +" "+am.getVardas()+" "+am.getMetai()+"\n"); 
        }
        else
            textar.append("\neile tuscia");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(eile.isEmpty()==true)
            textar.append("\nTRUE");
        else
            textar.append("\nFALSE");
            
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
//        String[] a = textfld.getText().split(    "");
//        String vard;
//        String Pavard;
//        int skc;      
//            vard = a[0];
//           Pavard = a[1];
//            skc = Integer.parseInt(a[2]);
//            Player abc = new Player(vard, Pavard, skc);      
        
                if(eile.Contains(a5)==true)
            textar.append("\nTRUE");
        else
            textar.append("\nFALSE");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling c
        Greitaveika();

    }//GEN-LAST:event_jButton6ActionPerformed

    
    Pq<Player> eile = new Pq<>();
     Player a3 = new Player.Builder().buildRandom();
        Player a4 = new Player("Cristiano", "Ronaldo", 2);                        
        Player a5 = new Player("Lionel", "Messi" ,70);
        Player a6 = new Player("Christian", "Eriksen", 5);
        Player a7 = new Player("Kyllian", "Mbappe", 8);
        Player a8 = new Player("Romelu", "Lukaku", 9);
        Player a9 = new Player("Karim", "Benzema", 4);
     Player[] zaidMasyvas = {a3, a4, a5, a6, a7, a8, a9};

     public void Greitaveika()
    { 
         System.out.println("");
         System.out.println("Greitaveika");
         
         long startTime = System.nanoTime();
         Pq testavimas = new Pq();
         for(int i=0; i < 20000; i++){
             Player a3 = new Player.Builder().buildRandom();
             testavimas.add(a3, a3.getMetai());
         }
             
        long endTime = System.nanoTime();
        System.out.println("Add, pridedame 20000elementu i eile: "
                +(double)(endTime - startTime)/1000000000  + "s");    
         //-------------------------------------------------------------------------
         // Contains metodo testavimas
         startTime= System.nanoTime();
         for(int i=0; i < 20000; i++)
         {
             testavimas.Contains(a3);
         }
         endTime = System.nanoTime();
        System.out.println("Contains, tikriname 20000elementu"
                + " : "+(double)(endTime - startTime)/1000000000  + "s");
        
         //-------------------------------------------------------------------------
         // Remove metodo testavimas
//         startTime= System.nanoTime();
//         for(int i=0; i < 10000; i++)
//         {
//             testavimas.();
//         }
//         endTime = System.nanoTime();
//        System.out.println("Salinama 10000elementu"
//                + " : "+(double)(endTime - startTime)/1000000000  + "s");
    } 


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textar;
    // End of variables declaration//GEN-END:variables
}
